server:
  port: 8103
  servlet:
    context-path: /api
spring:
  application:
    name: api-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
#      server-addr: 116.204.109.230:8848 # nacos地址
#      username: nacos
#      password: Jimmy@2333
  rabbitmq:
    host: 116.204.109.230
    port: 5672
    virtual-host: /apiHub
    username: hekmatyar
    password: Jimmy@2333
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true # 开启feign对sentinel的支持
logging:
  level:
    com.apihub.user: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: api-service
    description: "接口调用服务-接口文档"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.apihub.api.controller