server:
  port: 8100
  servlet:
    context-path: /api
spring:
  #  application:
  #    name: gateway-service
  #  profiles:
  #    active: dev
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  #    password: Jimmy@2333
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowCredentials: true
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
#      server-addr: 8.130.35.69:8848 # nacos地址
#      username: nacos
#      password: Jimmy@2333
#    gateway:
#      routes:
#        - id: user-service # 路由规则id，自定义，唯一
#          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
#          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
#            - Path=/api/user/**,/api/userRPC/** # 这里是以请求路径作为判断规则

logging:
  level:
    com.apihub: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

apihub:
  auth:
    # 无需token验证的路径
    excludePaths:
      - /api/user/login
      - /api/user/login/email
      - /api/user/oauth/login/gitee
      - /api/user/oauth/gitee/callback
      - /api/apiService/**
    # 需要AK验证的路径
    includePaths:
      - /api/apiService/**
  #      - /api/user/get/login