server:
  port: 8101
  servlet:
    context-path: /api
spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#      server-addr: 8.130.35.69:8848 # nacos地址
#      username: nacos
#      password: Jimmy@2333
  datasource:
    url: jdbc:mysql://8.130.35.69:3306/apihub
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Jimmy@2333
  # Redis 配置
  redis:
    database: 6
    host: 8.130.35.69
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: Jimmy@2333
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    com.apihub: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: user-service
    description: "用户服务接口文档"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.apihub.user.controller

apihub:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m